version: '3.5'

services:
  cobalt-api:
    build: .  # Build the Docker image using the local Dockerfile
    restart: unless-stopped
    container_name: cobalt-api
    init: true
    ports:
      - "9000:9000"  # Expose port 9000 for cobalt-api service
    environment:
      NODE_ENV: "production"
      PORT: "9000"
      API_URL: "https://p01--test-service--pzsk2zbg498p.code.run/"  # Replace with your instance's API URL
      API_NAME: "test-service"  # Replace with your instance's distinctive name
      COBALT_CONFIG: "src/config.json"  # Path to your config file
      COBALT_DATA: "src/data"  # Path to your data directory
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

  cobalt-web:
    image: ghcr.io/imputnet/cobalt:7
    restart: unless-stopped
    container_name: cobalt-web
    init: true
    ports:
      - "9001:9001"  # Expose port 9001 for cobalt-web service
    environment:
      NODE_ENV: "production"
      WEB_URL: "https://p01--test-service--pzsk2zbg498p.code.run/"  # Replace with your instance's web URL
      API_URL: "https://p01--test-service--pzsk2zbg498p.code.run/"  # Replace with your preferred API instance URL
      COBALT_CONFIG: "src/config.json"  # Path to your config file
      COBALT_DATA: "src/data"  # Path to your data directory
    labels:
      - com.centurylinklabs.watchtower.scope=cobalt

  watchtower:
    image: ghcr.io/containrrr/watchtower
    restart: unless-stopped
    command: --cleanup --scope cobalt --interval 900 --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
